CREATE TABLE `Posts` (
    `Id` INT NOT NULL AUTO_INCREMENT ,
    `Title` VARCHAR(3000) NOT NULL ,
    `Submit` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `Abstract` MEDIUMTEXT NOT NULL ,
    PRIMARY KEY (`Id`)) ENGINE = InnoDB;
ALTER TABLE `Posts` CHANGE `Abstract` `Abstract` MEDIUMTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL;
ALTER TABLE `Posts` ADD `Body` LONGTEXT NOT NULL AFTER `Abstract`;
ALTER TABLE `Posts` ADD `Type` VARCHAR(20) NULL AFTER `Body`;
ALTER TABLE `Posts` ADD `FileName` VARCHAR(3000) NULL AFTER `Type`;

CREATE TABLE `Files` (
 `Id` int(11) NOT NULL AUTO_INCREMENT,
 `FileName` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `Submit` datetime NOT NULL,
 `Status` enum('1','0') COLLATE utf8_unicode_ci NOT NULL DEFAULT '1',
 PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `Users` ( `Email` VARCHAR(255) NOT NULL , `Password` VARCHAR(3000) NOT NULL ) ENGINE = InnoDB;
ALTER TABLE `Users` ADD `Id` INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`Id`);

CREATE TABLE `Visits` (
    `Id` BIGINT NOT NULL AUTO_INCREMENT ,
    `Submit` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `CONTEXT_DOCUMENT_ROOT` VARCHAR(500) NULL ,
    `CONTEXT_PREFIX` VARCHAR(500) NULL ,
    `DOCUMENT_ROOT` VARCHAR(500) NULL ,
    `GATEWAY_INTERFACE` VARCHAR(500) NULL,
    `HTTP_ACCEPT` VARCHAR(500) NULL,
    `HTTP_ACCEPT_ENCODING` VARCHAR(500) NULL,
    `HTTP_ACCEPT_LANGUAGE` VARCHAR(500) NULL,
    `HTTP_CACHE_CONTROL` VARCHAR(500) NULL,
    `HTTP_CONNECTION` VARCHAR(500) NULL,
    `HTTP_COOKIE` VARCHAR(500) NULL,
    `HTTP_HOST` VARCHAR(500) NULL,
    `HTTP_REFERER` VARCHAR(500) NULL,
    `HTTP_SEC_FETCH_DEST` VARCHAR(500) NULL,
    `HTTP_SEC_FETCH_MODE` VARCHAR(500) NULL,
    `HTTP_SEC_FETCH_SITE` VARCHAR(500) NULL,
    `HTTP_SEC_FETCH_USER` VARCHAR(500) NULL,
    `HTTP_UPGRADE_INSECURE_REQUESTS` VARCHAR(500) NULL,
    `HTTP_USER_AGENT` VARCHAR(500) NULL,
    `PATH` VARCHAR(500) NULL,
    `PATH_INFO` VARCHAR(500) NULL,
    `PATH_TRANSLATED` VARCHAR(500) NULL,
    `PHP_SELF` VARCHAR(500) NULL,
    `QUERY_STRING` VARCHAR(500) NULL,
    `REDIRECT_STATUS` VARCHAR(500) NULL,
    `REDIRECT_URL` VARCHAR(500) NULL,
    `REMOTE_ADDR` VARCHAR(500) NULL,
    `REMOTE_PORT` VARCHAR(500) NULL,
    `REQUEST_METHOD` VARCHAR(500) NULL,
    `REQUEST_SCHEME` VARCHAR(500) NULL,
    `REQUEST_TIME` VARCHAR(500) NULL,
    `REQUEST_TIME_FLOAT` VARCHAR(500) NULL,
    `REQUEST_URI` VARCHAR(500) NULL,
    `SCRIPT_FILENAME` VARCHAR(500) NULL,
    `SCRIPT_NAME` VARCHAR(500) NULL,
    `SERVER_ADDR` VARCHAR(500) NULL,
    `SERVER_ADMIN` VARCHAR(500) NULL,
    `SERVER_NAME` VARCHAR(500) NULL,
    `SERVER_PORT` VARCHAR(500) NULL,
    `SERVER_PROTOCOL` VARCHAR(500) NULL,
    `SERVER_SIGNATURE` VARCHAR(500) NULL,
    `SERVER_SOFTWARE` VARCHAR(500) NULL,
    PRIMARY KEY (`Id`)) ENGINE = InnoDB;



CREATE TABLE `Comments` ( `Id` INT NOT NULL AUTO_INCREMENT , `Submit` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , `Body` VARCHAR(3000) NOT NULL , `EMail` VARCHAR(320) NULL , `Name` varchar(200) NULL , `PostId` INT NOT NULL , PRIMARY KEY (`Id`)) ENGINE = InnoDB;
ALTER TABLE `Comments` ADD CONSTRAINT `PostMustExist` FOREIGN KEY (`PostId`) REFERENCES `Posts`(`Id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `Comments` ADD `IsFromAdmin` BIT(1) NOT NULL DEFAULT b'0' AFTER `Name`,
ADD `IsPublic` BIT(1) NOT NULL DEFAULT b'1' AFTER `IsFromAdmin`,
ADD `IsVisible` BIT(1) NOT NULL DEFAULT b'0' AFTER `IsPublic`,
ADD `IsDeleted` BIT(1) NOT NULL DEFAULT b'0' AFTER `IsVisible`;